### ISSUE TITLE
Learning Python

### ISSUE THREAD

**Issue by kayaelle** [NaNoGenMo/2016#112]
Using NaNoGenMo as motivation for first python project.

**Comment by charlesreid1** [comment]
Leonardr's [olipy](https://github.com/leonardr/olipy) is a pretty rad and easy-to-use library for "artistic text generation." It has some really fun built-in examples and works right out of the box.

**Comment by kayaelle** [comment]
Thanks, @charlesreid1 ! Holidays got me off schedule. Will check this out and see if I can make a little something in the next couple of days.

**Comment by kayaelle** [comment]
Sadly didn't get back to this but did learn some python along the way.
