### ISSUE TITLE
Entry:  #NaNoProcJamGenMo Toying with recursively generated video game narrative

### ISSUE THREAD

**Issue by chipmonkey** [NaNoGenMo/2016#13]
I actually finished NaNoWriMo a couple of years ago, but with ProcJam this month I figured I'd give NaNoGenMo a try and kill three birds with one piece of code.  Hopefully.

I've no idea what I'm doing, but so what?!

In my head, my approach will be to build a recursive storytelling program that starts with a basic structure (provided or generated), then breaks it down and fills in details on each level of recursion.  That is, we start with a start and ending progression "A wizard gave a hobbit a ring.  The hobbit threw the ring into the lava." And the program fills in a story with additional starts and ends, always respecting the story line already created, just adding characters, text, progression, and whatnot one level at a time.

Will this work?  I've no idea.  But you've got to start somewhere.

**Comment by ikarth** [comment]
Sounds like a plan! There were a couple of generators last year that did stuff a little bit like that (particularly [this one](https://github.com/dariusk/NaNoGenMo-2015/issues/155)), but I think the space of recusively expanding story generators is still very, very underexplored. I look forward to seeing your results. You might also want to look at Tracery, logic programming, and maybe [Redwreath and Goldstar Have Traveled to Deathsgate](http://eblong.com/zarf/essays/r-and-g.html).

**Comment by tra38** [comment]
I'd also recommend looking at [A Time For Destiny](https://github.com/dariusk/NaNoGenMo-2015/issues/11#issue-113341430) and [its Story Compiler approach](https://gist.github.com/cpressey/6324fff6ef0dfdf69b96), for information on how to set up a basic storyline structure that can then be expanded with more information. ("A wizard gave a hobbit a ring. The hobbit threw the ring into the lava." is very similar to that of the 'null plot' concept in the Story Compiler.)

**Comment by chipmonkey** [comment]
I'm updating the plan slightly.  Since we're closely tied to ProcJam, and since I'm part of LouisvilleMakesGames, where we run a lot of video game jams, I'm hoping to combine the three elements.  Still building a recursive story line, but that recursion will take the form of "Quests"... Each split will (this is all theory) include side goals (quests) that include characters, objectives, locations, and narrative progress around those things.  I think this will help me keep track of the narrative "state" better.  Where is every character?  What have they done, who are they interacting with, what is their motivation?  Daunting for 30 days.  I won't finish... but we'll see where we get.

Thanks for the input so far!

**Comment by chipmonkey** [comment]
Ok, didn't make it this year... and the rest of the day isn't going to make the difference.  But it was good to watch everyone work, and I learned a few things!  Maybe next year!
