### ISSUE TITLE
Ciphered Short Stories

### ISSUE THREAD

**Issue by willf** [NaNoGenMo/2016#29]
Since I've recently joined GitHub, I think it might be interesting to tail the activity log and either generate a screen play or short chapters based on them. PERHAPS ON THE NANOGENMO REPOS THEMSELVES.

**Comment by MichaelPaulukonis** [comment]
[Prior Art](https://github.com/dariusk/NaNoGenMo-2015/issues/162) that is woefully incomplete, and taking a somewhat diffferent tack.

I should really finish this - I particularly want to be able to extract more data like languages used, etc.

**Comment by willf** [comment]
Thanks @MichaelPaulukonis Still pondering ...

**Comment by willf** [comment]
Well, I didn't write the Great American GitHub novel, but I did do something that was a lot of fun:

[twenty-six: simply ciphered classic shorts](https://github.com/willf/NaNoGenMo-2016/blob/master/results/twenty-six.pdf) at my [NaNoGenMo-2016](https://github.com/willf/NaNoGenMo-2016) repo.

**Comment by willf** [comment]
@MichaelPaulukonis You can mark this as completed and with preview available.

**Comment by hugovk** [comment]
@willf Congrats and labelled! I like it! I also had problems trying to find something that could save Unicode emoji to PDF, I'l try out Apple's Pages too.

The preview label means there's a preview shown in the issue, without having to click through. So:

> _The Tell-Tale Heart_ is a classic Poe story, first published in 1843. The text used here is from
Project Gutenberg. The cipher is between the five vowels and various Unicode heart emojis.

> Tr♥❤!—n❤rv☙♥s—v❤ry, v❤ry dr❤❦df♥lly n❤rv☙♥s ❧ h❦d b❤❤n ❦nd ❦m; b♥t why w❧ll
y☙♥ s❦y th❦t ❧ ❦m m❦d? Th❤ d❧s❤❦s❤ h❦d sh❦rp❤n❤d my s❤ns❤s—n☙t d❤str☙y❤d
—n☙t d♥ll❤d th❤m. ❦b☙v❤ ❦ll w❦s th❤ s❤ns❤ ☙f h❤❦r❧ng ❦c♥t❤. ❧ h❤❦rd ❦ll
th❧ngs ❧n th❤ h❤❦v❤n ❦nd ❧n th❤ ❤❦rth. ❧ h❤❦rd m❦ny th❧ngs ❧n h❤ll. H☙w, th❤
n, ❦m ❧ m❦d? H❤❦rk❤n! ❦nd ☙bs❤rv❤ h☙w h❤❦lth❧ly—h☙w c❦lmly ❧ c❦n t❤ll y☙♥ th
❤ wh☙l❤ st☙ry.

**Comment by willf** [comment]
Thanks, @hugovk – and thanks to all the tender carers.
